/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MctInput {
        "name"?: string;
        "value"?: string;
    }
    interface MctTestComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
}
declare global {
    interface HTMLMctInputElement extends Components.MctInput, HTMLStencilElement {
    }
    var HTMLMctInputElement: {
        prototype: HTMLMctInputElement;
        new (): HTMLMctInputElement;
    };
    interface HTMLMctTestComponentElement extends Components.MctTestComponent, HTMLStencilElement {
    }
    var HTMLMctTestComponentElement: {
        prototype: HTMLMctTestComponentElement;
        new (): HTMLMctTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "mct-input": HTMLMctInputElement;
        "mct-test-component": HTMLMctTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface MctInput {
        "name"?: string;
        "value"?: string;
    }
    interface MctTestComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "mct-input": MctInput;
        "mct-test-component": MctTestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mct-input": LocalJSX.MctInput & JSXBase.HTMLAttributes<HTMLMctInputElement>;
            "mct-test-component": LocalJSX.MctTestComponent & JSXBase.HTMLAttributes<HTMLMctTestComponentElement>;
        }
    }
}
